# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x0e\x63inema.auth.v1\"D\n\x0fRegisterRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\"/\n\x0cLoginRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"i\n\rLoginResponse\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x1a\n\x12\x65xpires_in_seconds\x18\x02 \x01(\x03\x12&\n\x04user\x18\x03 \x01(\x0b\x32\x18.cinema.auth.v1.AuthUser\",\n\x14ValidateTokenRequest\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\"E\n\x15ValidateTokenResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0c\n\x04role\x18\x03 \x01(\t\"!\n\x0eGetUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\":\n\x10\x41uthUserResponse\x12&\n\x04user\x18\x01 \x01(\x0b\x32\x18.cinema.auth.v1.AuthUser\"_\n\x08\x41uthUser\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x0c\n\x04role\x18\x04 \x01(\t\x12\x18\n\x10\x63reated_at_epoch\x18\x05 \x01(\x03\x32\xcd\x02\n\x0b\x41uthService\x12M\n\x08Register\x12\x1f.cinema.auth.v1.RegisterRequest\x1a .cinema.auth.v1.AuthUserResponse\x12\x44\n\x05Login\x12\x1c.cinema.auth.v1.LoginRequest\x1a\x1d.cinema.auth.v1.LoginResponse\x12\\\n\rValidateToken\x12$.cinema.auth.v1.ValidateTokenRequest\x1a%.cinema.auth.v1.ValidateTokenResponse\x12K\n\x07GetUser\x12\x1e.cinema.auth.v1.GetUserRequest\x1a .cinema.auth.v1.AuthUserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERREQUEST']._serialized_start=30
  _globals['_REGISTERREQUEST']._serialized_end=98
  _globals['_LOGINREQUEST']._serialized_start=100
  _globals['_LOGINREQUEST']._serialized_end=147
  _globals['_LOGINRESPONSE']._serialized_start=149
  _globals['_LOGINRESPONSE']._serialized_end=254
  _globals['_VALIDATETOKENREQUEST']._serialized_start=256
  _globals['_VALIDATETOKENREQUEST']._serialized_end=300
  _globals['_VALIDATETOKENRESPONSE']._serialized_start=302
  _globals['_VALIDATETOKENRESPONSE']._serialized_end=371
  _globals['_GETUSERREQUEST']._serialized_start=373
  _globals['_GETUSERREQUEST']._serialized_end=406
  _globals['_AUTHUSERRESPONSE']._serialized_start=408
  _globals['_AUTHUSERRESPONSE']._serialized_end=466
  _globals['_AUTHUSER']._serialized_start=468
  _globals['_AUTHUSER']._serialized_end=563
  _globals['_AUTHSERVICE']._serialized_start=566
  _globals['_AUTHSERVICE']._serialized_end=899
# @@protoc_insertion_point(module_scope)
