# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cinema.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cinema.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63inema.proto\x12\x11\x63inema.catalog.v1\"-\n\x11ListMoviesRequest\x12\x18\n\x10include_upcoming\x18\x01 \x01(\x08\">\n\x12ListMoviesResponse\x12(\n\x06movies\x18\x01 \x03(\x0b\x32\x18.cinema.catalog.v1.Movie\"#\n\x0fGetMovieRequest\x12\x10\n\x08movie_id\x18\x01 \x01(\t\"8\n\rMovieResponse\x12\'\n\x05movie\x18\x01 \x01(\x0b\x32\x18.cinema.catalog.v1.Movie\":\n\x14ListShowtimesRequest\x12\x10\n\x08movie_id\x18\x01 \x01(\t\x12\x10\n\x08\x64\x61te_iso\x18\x02 \x01(\t\"G\n\x15ListShowtimesResponse\x12.\n\tshowtimes\x18\x01 \x03(\x0b\x32\x1b.cinema.catalog.v1.Showtime\"(\n\x11GetSeatMapRequest\x12\x13\n\x0bshowtime_id\x18\x01 \x01(\t\"<\n\x12GetSeatMapResponse\x12&\n\x05seats\x18\x01 \x03(\x0b\x32\x17.cinema.catalog.v1.Seat\"v\n\x05Movie\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x18\n\x10\x64uration_minutes\x18\x04 \x01(\x05\x12\x0e\n\x06rating\x18\x05 \x01(\t\x12\x13\n\x0bnow_showing\x18\x06 \x01(\x08\"d\n\x08Showtime\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08movie_id\x18\x02 \x01(\t\x12\x0c\n\x04room\x18\x03 \x01(\t\x12\x16\n\x0estart_time_iso\x18\x04 \x01(\t\x12\x14\n\x0c\x65nd_time_iso\x18\x05 \x01(\t\"D\n\x04Seat\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\x14\n\x0cis_available\x18\x03 \x01(\x08\x12\x0c\n\x04type\x18\x04 \x01(\t2\xfb\x02\n\rCinemaService\x12Y\n\nListMovies\x12$.cinema.catalog.v1.ListMoviesRequest\x1a%.cinema.catalog.v1.ListMoviesResponse\x12P\n\x08GetMovie\x12\".cinema.catalog.v1.GetMovieRequest\x1a .cinema.catalog.v1.MovieResponse\x12\x62\n\rListShowtimes\x12\'.cinema.catalog.v1.ListShowtimesRequest\x1a(.cinema.catalog.v1.ListShowtimesResponse\x12Y\n\nGetSeatMap\x12$.cinema.catalog.v1.GetSeatMapRequest\x1a%.cinema.catalog.v1.GetSeatMapResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cinema_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LISTMOVIESREQUEST']._serialized_start=35
  _globals['_LISTMOVIESREQUEST']._serialized_end=80
  _globals['_LISTMOVIESRESPONSE']._serialized_start=82
  _globals['_LISTMOVIESRESPONSE']._serialized_end=144
  _globals['_GETMOVIEREQUEST']._serialized_start=146
  _globals['_GETMOVIEREQUEST']._serialized_end=181
  _globals['_MOVIERESPONSE']._serialized_start=183
  _globals['_MOVIERESPONSE']._serialized_end=239
  _globals['_LISTSHOWTIMESREQUEST']._serialized_start=241
  _globals['_LISTSHOWTIMESREQUEST']._serialized_end=299
  _globals['_LISTSHOWTIMESRESPONSE']._serialized_start=301
  _globals['_LISTSHOWTIMESRESPONSE']._serialized_end=372
  _globals['_GETSEATMAPREQUEST']._serialized_start=374
  _globals['_GETSEATMAPREQUEST']._serialized_end=414
  _globals['_GETSEATMAPRESPONSE']._serialized_start=416
  _globals['_GETSEATMAPRESPONSE']._serialized_end=476
  _globals['_MOVIE']._serialized_start=478
  _globals['_MOVIE']._serialized_end=596
  _globals['_SHOWTIME']._serialized_start=598
  _globals['_SHOWTIME']._serialized_end=698
  _globals['_SEAT']._serialized_start=700
  _globals['_SEAT']._serialized_end=768
  _globals['_CINEMASERVICE']._serialized_start=771
  _globals['_CINEMASERVICE']._serialized_end=1150
# @@protoc_insertion_point(module_scope)
