# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: order.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'order.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0border.proto\x12\x0f\x63inema.order.v1\"d\n\x12\x43reateOrderRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x13\n\x0bshowtime_id\x18\x02 \x01(\t\x12\x10\n\x08seat_ids\x18\x03 \x03(\t\x12\x16\n\x0epayment_method\x18\x04 \x01(\t\"#\n\x0fGetOrderRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\"*\n\x17ListOrdersByUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"B\n\x18ListOrdersByUserResponse\x12&\n\x06orders\x18\x01 \x03(\x0b\x32\x16.cinema.order.v1.Order\"6\n\x12\x43\x61ncelOrderRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0e\n\x06reason\x18\x02 \x01(\t\",\n\x18StreamOrderStatusRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\"_\n\x10OrderStatusEvent\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x18\n\x10\x65vent_time_epoch\x18\x04 \x01(\x03\"6\n\rOrderResponse\x12%\n\x05order\x18\x01 \x01(\x0b\x32\x16.cinema.order.v1.Order\"\x9c\x01\n\x05Order\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x13\n\x0bshowtime_id\x18\x03 \x01(\t\x12\x10\n\x08seat_ids\x18\x04 \x03(\t\x12\x0e\n\x06status\x18\x05 \x01(\t\x12\x13\n\x0btotal_price\x18\x06 \x01(\x03\x12\x10\n\x08\x63urrency\x18\x07 \x01(\t\x12\x18\n\x10\x63reated_at_epoch\x18\x08 \x01(\x03\x32\xd2\x03\n\x0cOrderService\x12R\n\x0b\x43reateOrder\x12#.cinema.order.v1.CreateOrderRequest\x1a\x1e.cinema.order.v1.OrderResponse\x12L\n\x08GetOrder\x12 .cinema.order.v1.GetOrderRequest\x1a\x1e.cinema.order.v1.OrderResponse\x12g\n\x10ListOrdersByUser\x12(.cinema.order.v1.ListOrdersByUserRequest\x1a).cinema.order.v1.ListOrdersByUserResponse\x12R\n\x0b\x43\x61ncelOrder\x12#.cinema.order.v1.CancelOrderRequest\x1a\x1e.cinema.order.v1.OrderResponse\x12\x63\n\x11StreamOrderStatus\x12).cinema.order.v1.StreamOrderStatusRequest\x1a!.cinema.order.v1.OrderStatusEvent0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEORDERREQUEST']._serialized_start=32
  _globals['_CREATEORDERREQUEST']._serialized_end=132
  _globals['_GETORDERREQUEST']._serialized_start=134
  _globals['_GETORDERREQUEST']._serialized_end=169
  _globals['_LISTORDERSBYUSERREQUEST']._serialized_start=171
  _globals['_LISTORDERSBYUSERREQUEST']._serialized_end=213
  _globals['_LISTORDERSBYUSERRESPONSE']._serialized_start=215
  _globals['_LISTORDERSBYUSERRESPONSE']._serialized_end=281
  _globals['_CANCELORDERREQUEST']._serialized_start=283
  _globals['_CANCELORDERREQUEST']._serialized_end=337
  _globals['_STREAMORDERSTATUSREQUEST']._serialized_start=339
  _globals['_STREAMORDERSTATUSREQUEST']._serialized_end=383
  _globals['_ORDERSTATUSEVENT']._serialized_start=385
  _globals['_ORDERSTATUSEVENT']._serialized_end=480
  _globals['_ORDERRESPONSE']._serialized_start=482
  _globals['_ORDERRESPONSE']._serialized_end=536
  _globals['_ORDER']._serialized_start=539
  _globals['_ORDER']._serialized_end=695
  _globals['_ORDERSERVICE']._serialized_start=698
  _globals['_ORDERSERVICE']._serialized_end=1164
# @@protoc_insertion_point(module_scope)
