# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import cinema_service.project.grpc.cinema_pb2 as cinema__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cinema_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CinemaServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListMovies = channel.unary_unary(
                '/cinema.catalog.v1.CinemaService/ListMovies',
                request_serializer=cinema__pb2.ListMoviesRequest.SerializeToString,
                response_deserializer=cinema__pb2.ListMoviesResponse.FromString,
                _registered_method=True)
        self.GetMovie = channel.unary_unary(
                '/cinema.catalog.v1.CinemaService/GetMovie',
                request_serializer=cinema__pb2.GetMovieRequest.SerializeToString,
                response_deserializer=cinema__pb2.MovieResponse.FromString,
                _registered_method=True)
        self.ListShowtimes = channel.unary_unary(
                '/cinema.catalog.v1.CinemaService/ListShowtimes',
                request_serializer=cinema__pb2.ListShowtimesRequest.SerializeToString,
                response_deserializer=cinema__pb2.ListShowtimesResponse.FromString,
                _registered_method=True)
        self.GetSeatMap = channel.unary_unary(
                '/cinema.catalog.v1.CinemaService/GetSeatMap',
                request_serializer=cinema__pb2.GetSeatMapRequest.SerializeToString,
                response_deserializer=cinema__pb2.GetSeatMapResponse.FromString,
                _registered_method=True)


class CinemaServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListMovies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMovie(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListShowtimes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSeatMap(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CinemaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListMovies': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMovies,
                    request_deserializer=cinema__pb2.ListMoviesRequest.FromString,
                    response_serializer=cinema__pb2.ListMoviesResponse.SerializeToString,
            ),
            'GetMovie': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMovie,
                    request_deserializer=cinema__pb2.GetMovieRequest.FromString,
                    response_serializer=cinema__pb2.MovieResponse.SerializeToString,
            ),
            'ListShowtimes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListShowtimes,
                    request_deserializer=cinema__pb2.ListShowtimesRequest.FromString,
                    response_serializer=cinema__pb2.ListShowtimesResponse.SerializeToString,
            ),
            'GetSeatMap': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSeatMap,
                    request_deserializer=cinema__pb2.GetSeatMapRequest.FromString,
                    response_serializer=cinema__pb2.GetSeatMapResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cinema.catalog.v1.CinemaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cinema.catalog.v1.CinemaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CinemaService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListMovies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cinema.catalog.v1.CinemaService/ListMovies',
            cinema__pb2.ListMoviesRequest.SerializeToString,
            cinema__pb2.ListMoviesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMovie(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cinema.catalog.v1.CinemaService/GetMovie',
            cinema__pb2.GetMovieRequest.SerializeToString,
            cinema__pb2.MovieResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListShowtimes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cinema.catalog.v1.CinemaService/ListShowtimes',
            cinema__pb2.ListShowtimesRequest.SerializeToString,
            cinema__pb2.ListShowtimesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSeatMap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cinema.catalog.v1.CinemaService/GetSeatMap',
            cinema__pb2.GetSeatMapRequest.SerializeToString,
            cinema__pb2.GetSeatMapResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
